name: Sync Repositories

on:
  push:
    branches:
      - main # Replace with the branch you want to sync

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Repository
      uses: actions/checkout@v3

    - name: Setup SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H github.com >> ~/.ssh/known_hosts

    - name: Add Destination Repository as Remote
      run: |
        git remote add destination git@github.com:nileshA-addweb/bhardwaj-testing.git
        git fetch destination

    - name: Push Changes to Destination Repository
      run: |
        git push destination main --force

