name: Sync Repositories

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Repository
      uses: actions/checkout@v3

    - name: Add Destination Repository as Remote
      run: |
        ls
        rm -rf .git
        ls
        git init
        ls
        git remote add origin https://${{secrets.GH_USER}}:${{secrets.GH_PAT}}@github.com/nileshA-addweb/bhardwaj-testing.git
        git config --global user.email "nilesh@addwebsolution.in"
        git config --global user.name "nileshA-addweb"
        ls
        echo remote
        git remote -v
        echo fetch 
        git fetch --all
        echo pull
        git pull origin main 
        git add .
        git commit -m "Sync changes"

    - name: Fetch Shallow History and Push
      run: |
        git push https://${{secrets.GH_USER}}:${{secrets.GH_PAT}}@github.com/nileshA-addweb/bhardwaj-testing.git main


