name: Sync Repositories

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Repository
      uses: actions/checkout@v3

    - name: Add Destination Repository as Remote
      run: |
        rm -rf .git
        git init
        git remote add origin https://${{secrets.GH_USER}}:${{secrets.GH_PAT}}@github.com/nileshA-addweb/bhardwaj-testing.git
        git config --global user.email "nilesh@addwebsolution.in"
        git config --global user.name "nileshA-addweb"
        ls
        echo remote
        git remote -v
        echo fetch
        git fetch --all 
        git branch -b main
        echo branch name
        git branch
        git add .
        git commit -m "Sync changes"
        git push -f origin main

