name: Sync Repositories

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Add Destination Repository as Remote
      run: |
        rm -rf .git
        git init
        git remote add origin https://github.com/nileshA-addweb/bhardwaj-testing.git
        git config --global user.email "bhardwaj.28.m@gmail.com"
        git config --global user.name "bhardwajmishra"
        git remote -v
        git branch -m main
        git add .
        git commit -m "Sync changes"

    - name: Fetch Shallow History and Push
      run: |
        git push origin https://${{secrets.GH_USER}}:${{secrets.GH_PAT}}@github.com/nileshA-addweb/bhardwaj-testing.git main


