name: Sync Repositories

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Repository
      uses: actions/checkout@v3
    - name: Add Destination Repository as Remote
      run: |
        rm -rf .git
        git init
        git remote add origin https://github.com/nileshA-addweb/bhardwaj-testing.git
        git config --global user.email "bhardwaj.28.m@gmail.com"
        git config --global user.name "bhardwajmishra"
        git remote -v
        git checkout -b main
        git fetch --all
        git add  .
        git commit -m "initial commit"

    - name: Fetch Shallow History and Push
      run: |
        git push https://${{secrets.GH_USER}}:${{secrets.GH_PAT}}@github.com/nileshA-addweb/bhardwaj-testing.git main


